version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    environment:
      DATABASE_HOST: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0 

      #  webpack_dev_server:
      #    build: .
      #    command: ./bin/webpack-dev-server
      #    ports:
      #      - 3035:3035
      #    volumes:
      #      - .:/usr/src/app
      #    environment:
      #      DATABASE_HOST: database
      #      POSTGRES_USER: postgres
      #      POSTGRES_PASSWORD: password
      #      POSTGRES_DB: myapp_development
      #      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0 

  redis:
    image: redis
  
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  gem_cache:
